version: '3'

services:
  app:
    build: .
    container_name: agora_app
    ports:
      - "4002:4001"
    depends_on:
      - db
      - cache
    environment:
      - PORT=4002
      - LOCAL_DEVELOPMENT=true
      - REDIS_HOST=redis://cache:6379
      - DB_HOST=db
      - DB_DATABASE=agora_db
      - DB_USER=agora_user_1
      - DB_PASSWORD=pass1234
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=
      - GOOGLE_SHEET_ID=
      - GOOGLE_PRIVATE_KEY=
      # wait until the MySQL db is ready before attempting to connect the Express app to it
      - WAIT_HOSTS=db:3306
  db:
    image: mysql:5.7
    container_name: agora_mysql
    restart: always
    volumes:
    # copy 'sql-scripts' directory to the container. All files in 'docker-entrypoint-initdb.d' 
    # will be automatically processed (in alphabetical order). See https://hub.docker.com/_/mysql
    - ./data/mysql/migration-script:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: agora_db
    ports:
      - "3308:3306"
  cache:
    image: redis
    ports:
      - 6379