version: '3'

services:
  app:
    build: .
    container_name: agora_app
    ports:
      - "4002:4001"
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
  mysql:
    image: mysql:8.0.17
    container_name: agora_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: agora_db
    ports:
      - "3308:3306"